Added field service cloudbuild

diff --git a/hooks/pull_request b/hooks/pull_request
--- a/hooks/pull_request
+++ b/hooks/pull_request
@@ -14,6 +14,9 @@ ORG_NAME=$(echo $REPO_URL | cut -d"/" -f4)
 
 case "$PR_ACTION" in
   opened|edited)
+    # Loading functions
+    source $(dirname $0)/../functions/functions.sh
+
     echo "${GCP_KEY}" > /tmp/key.json
     echo "Building for ${PR_ACTION}, ${PR_ID}, ${REPO_URL}, ${COMMIT_ID}"
     gcloud auth activate-service-account --key-file=/tmp/key.json
@@ -32,6 +35,10 @@ case "$PR_ACTION" in
       # Repo is for IAC, we copy the cloudbuild file for terraform
       echo "Found IAC terraform project"
       cp -af /app/cloudbuild_files/cloudbuild_terraform.yaml ./cloudbuild.yaml
+    elif [ "${REPO_NAME}" == "lmes-fsa-customization" ]; then
+      # Repo is for field service customization, we copy the cloudbuild file 
+      echo "Found field service customization project"
+      cp -af /app/cloudbuild_files/cloudbuild_field_service.yaml ./cloudbuild.yaml
     else
       echo "Copying generic file"
       cp -af /app/cloudbuild_files/cloudbuild.yaml .
@@ -42,9 +49,18 @@ case "$PR_ACTION" in
     gsutil cp /tmp/${REPO_NAME}_${PR_ID}_${DATE}.tar.gz gs://${GS_BUCKET_NAME}
     #gcloud config set builds/use_kaniko True
     gcloud config set project ${GCP_PROJECT_NAME}
-    gcloud builds submit gs://${GS_BUCKET_NAME}/${REPO_NAME}_${PR_ID}_${DATE}.tar.gz --async --substitutions SHORT_SHA=${COMMIT_SHA},REPO_NAME=${REPO_NAME},_ORG_NAME=${ORG_NAME},COMMIT_SHA=${COMMIT_ID},TAG_NAME=${VERSION}
+
+    # Getting configuration of allinconfig and setting subs_allinconfig var
+    get_configuration_allinconfig
+    [ $? -ne 0 ] && { echo "ERROR: Not getting configuration of allinconfig"; exit 1; } 
+
+    gcloud builds submit gs://${GS_BUCKET_NAME}/${REPO_NAME}_${PR_ID}_${DATE}.tar.gz --async --substitutions SHORT_SHA=${COMMIT_SHA},REPO_NAME=${REPO_NAME},_ORG_NAME=${ORG_NAME},COMMIT_SHA=${COMMIT_ID},TAG_NAME=${VERSION}${subs_allinconfig}
+    ret=$?
   ;;
   *)
     echo "Skipping pull request event type $PR_ACTION"
+    ret=0
   ;;
 esac
+ 
+exit $ret
diff --git a/hooks/release b/hooks/release
--- a/hooks/release
+++ b/hooks/release
@@ -14,6 +14,9 @@ ORG_NAME=$(echo $REPO_URL | cut -d"/" -f4)
 
 case "$R_ACTION" in
   published)
+    # Loading functions
+    source $(dirname $0)/../functions/functions.sh
+
     echo "${GCP_KEY}" > /tmp/key.json
     echo "Building for ${R_ACTION}, ${TAG_NAME}, ${REPO_URL}"
     gcloud auth activate-service-account --key-file=/tmp/key.json
@@ -33,6 +36,11 @@ case "$R_ACTION" in
       # Repo is for IAC, we copy the cloudbuild file for terraform
       echo "Found IAC terraform project"
       cp -af /app/cloudbuild_files/cloudbuild_terraform.yaml ./cloudbuild.yaml
+
+    elif [ "${REPO_NAME}" == "lmes-fsa-customization" ]; then
+      # Repo is for field service customization, we copy the cloudbuild file
+      echo "Found field service customization project"
+      cp -af /app/cloudbuild_files/cloudbuild_field_service.yaml ./cloudbuild.yaml
     else
       # Copy the generic file
       echo "Copying generic file"
@@ -45,12 +53,18 @@ case "$R_ACTION" in
     gsutil cp /tmp/${TAG_NAME}.tar.gz gs://${GS_BUCKET_NAME}
     #gcloud config set builds/use_kaniko True
     gcloud config set project ${GCP_PROJECT_NAME}
+
+    # Getting configuration of allinconfig
+    get_configuration_allinconfig
+    [ $? -ne 0 ] && { echo "ERROR: Not getting configuration of allinconfig"; exit 1; } 
+
     #gcloud builds submit gs://${GS_BUCKET_NAME}/${TAG_NAME}.tar.gz --async -t ${TAG_NAME} --substitutions TAG_NAME=${TAG_NAME},REPO_NAME=${REPO_NAME},_ORG_NAME=${ORG_NAME}
-    gcloud builds submit gs://${GS_BUCKET_NAME}/${TAG_NAME}.tar.gz --async --substitutions TAG_NAME=${TAG_NAME},REPO_NAME=${REPO_NAME},_ORG_NAME=${ORG_NAME}
+    gcloud builds submit gs://${GS_BUCKET_NAME}/${TAG_NAME}.tar.gz --async --substitutions TAG_NAME=${TAG_NAME},REPO_NAME=${REPO_NAME},_ORG_NAME=${ORG_NAME}${subs_allinconfig}
     ret=$?
   ;;
   *)
     echo "Skipping release event type $R_ACTION"
+    ret=0
   ;;
 esac
 
