feat(hooks): Force to use allinconfig loader

diff --git a/hooks/push b/hooks/push
--- a/hooks/push
+++ b/hooks/push
@@ -16,6 +16,8 @@ REPO_NAME=$(jq -r ".repository.name" $JSON_FILE)
 COMMIT_SHA=$(echo ${COMMIT_ID} | cut -c1-7)
 ORG_NAME=$(echo $REPO_URL | cut -d"/" -f4)
 
+runAllinconfigLoader=1
+
 # Loading functions
 source $(dirname $0)/../functions/functions.sh
 
@@ -52,19 +54,21 @@ elif [ "${REPO_NAME}" == "lmes-fsa-customization" ]; then
     # Repo is for field service customization, we copy the cloudbuild file 
     echo "Found field service customization project"
     cp -af /app/cloudbuild_files/cloudbuild_field_service.yaml ./cloudbuild.yaml
+
+    # Run allinconfig loader
+    runAllinconfigLoader=0
 else
     echo "Copying generic file"
     cp -af /app/cloudbuild_files/cloudbuild.yaml .
 fi
 
-# Getting configuration of allinconfig and setting subs_allinconfig var
-get_configuration_allinconfig
-
-if [ $? -eq 0 ]; then
-    gcloud builds submit gs://${GS_BUCKET_NAME}/${COMMIT_ID}.tar.gz --async --config cloudbuild.yaml --substitutions SHORT_SHA=${COMMIT_SHA},REPO_NAME=${REPO_NAME},_ORG_NAME=${ORG_NAME},COMMIT_SHA=${COMMIT_ID},TAG_NAME=${TAG_NAME}${subs_allinconfig}
-    ret=$?
-else
-    echo "ERROR: Not getting configuration of allinconfig"
+if [ $runAllinconfigLoader -eq 0 ]; then
+   # Getting configuration of allinconfig and setting subs_allinconfig var
+   get_configuration_allinconfig
+   [ $? -ne 0 ] && { echo "ERROR: Not getting configuration of allinconfig"; exit 1; }
 fi
+
+gcloud builds submit gs://${GS_BUCKET_NAME}/${COMMIT_ID}.tar.gz --async --config cloudbuild.yaml --substitutions SHORT_SHA=${COMMIT_SHA},REPO_NAME=${REPO_NAME},_ORG_NAME=${ORG_NAME},COMMIT_SHA=${COMMIT_ID},TAG_NAME=${TAG_NAME}${subs_allinconfig}
+ret=$?
 
 exit ${ret:-1}
